name: 'PageUp Code Coverage Action'
author: "PageUp"
description: "Execute code coverage analysis"
runs:
  using: "composite"
  steps:
    - run: dotnet tool install --global dotnet-coverage
      shell: bash
      
    - run: curl  https://raw.githubusercontent.com/PageUpPeopleOrg/pageup-code-coverage-action/main/automated.runsettings -o automated.runsettings
      shell: bash
      
    - run: find . -name "*.sln" -exec dotnet build {} --configuration Release \;
      shell: bash
  
    - run: find . -name "*.sln" -exec sh -c 'dotnet coverage collect "dotnet test "$1" --no-build --no-restore" --settings:coverage.settings --output ./Tests/CodeCoverage-$(basename "$1") --output-format cobertura' sh {} \;
      shell: bash

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: Tests/*cobertura.xml
        badge: true
        fail_below_min: false
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
